### ISSUE TITLE
check-redis-list-length.rb does not check to see if the Redis key is even valid.

### ISSUE THREAD

**Issue by NeckBeardPrince** [sensu-plugins/sensu-plugins-redis#10]
sensu-plugins-redis (0.0.4)

check-redis-list-length.rb -h redishost.amazonaws.com -w 10 -c 20 -k gmoprqgpiorewgoprwmghoprewmhoprt

RedisListLengthCheck OK: Redis list gmoprqgpiorewgoprwmghoprewmhoprt length is below thresholds

Promise that isn't a key :)

**Comment by eheydrick** [comment]
@NeckBeardPrince should it return unknown if the key doesn't exist? That would be easy to add. I'd take a PR for that.
