### ISSUE TITLE
Memory check in % rather than fixed value.

### ISSUE THREAD

**Issue by zerOnepal** [sensu-plugins/sensu-plugins-redis#11]
This is more kind of feature request.. than a issue on [this](https://github.com/sensu-plugins/sensu-plugins-redis/blob/master/bin/check-redis-memory.rb#L35-L47)

The options memory usage by redis in percentage is more easy to manage(scale) than the direct absolute values in KB. Any thought on this ? 

Also, I am missing the important metrics: throughput and latency metrics meausresments...
Any future plans for these ? 

*Monitoring my 15+ REDIS minons would be much easire with above requested features* :neckbeard: 

Thanks

**Comment by zerOnepal** [comment]
Since i got my pull requet merged.. https://github.com/sensu-plugins/sensu-plugins-redis/pull/12 . closing this for now... 

thanks team

**Comment by eheydrick** [comment]
Thanks for the contribution @zerOnepal!

**Comment by zerOnepal** [comment]
Pleasure @eheydrick
its all my brothers @xhagrg, @bisusubedi who pampered me in this scary world of ruby. 
kudos all  :feelsgood:
