### ISSUE TITLE
variable is not resolved in output message

### ISSUE THREAD

**Issue by BrotherCheng** [sensu-plugins/sensu-plugins-redis#14]
https://github.com/sensu-plugins/sensu-plugins-redis/blob/master/bin/check-redis-memory-percentage.rb#L89

Should use double quotation marks instead.

Seems should update check-redis-memory.rb too.

**Comment by zerOnepal** [comment]
@BrotherCheng sorry, my bad, :see_no_evil: 
this pull https://github.com/sensu-plugins/sensu-plugins-redis/pull/15 will do the job

**Comment by eheydrick** [comment]
Fix will go out in next release.
