### ISSUE TITLE
Gimme, gimme!

### ISSUE THREAD

**Issue by josephholsten** [sensu-plugins/sensu-plugins-redis#2]
What's needed to officially release this into rubygems? Anything I can help with?

**Comment by mattyjones** [comment]
@josephholsten 

We just need to add it to the deployment pipeline.  Nothing is built manually.  It should be a gem by Monday morning.

**Comment by sarkis** [comment]
Was trying to install via the README's recommended way for chef and getting the following:

failed to find gem sensu-plugins-redis (= 0.0.1.alpha.4) from [https://rubygems.org/]

Was assuming its still not in rubygems

**Comment by mattyjones** [comment]
@sarkis @josephholsten 

it is now
