### ISSUE TITLE
check-redis-slave-status does not support Sentinel managed Master switch over

### ISSUE THREAD

**Issue by arslanm** [sensu-plugins/sensu-plugins-redis#20]
When a master and multiple slave setup is configured to be monitored by Redis Sentinels, if a master switch over is issued by the Sentinels in the case of a master failure, the script check-redis-slave-status.rb starts returning "critical" on the old-slave/new-master, at line #44.

**Comment by majormoses** [comment]
can you conform this is resolved in version `1.1.0`? If so we can close this.

**Comment by stevenviola** [comment]
1.1.0 fixes this issue for me. Thanks!

**Comment by majormoses** [comment]
closing per: https://github.com/sensu-plugins/sensu-plugins-redis/issues/20#issuecomment-298932893
