### ISSUE TITLE
Incompatible metrics

### ISSUE THREAD

**Issue by TheKevJames** [sensu-plugins/sensu-plugins-redis#22]
Looks like some of the metrics generated by `metrics-redis-graphite.rb` are incompatible with graphite. As far as I can tell, `SKIP_KEYS_REGEX` is supposed to filter these out. Maybe it needs to be updated to include the following keys?

Error(s):

```
[listener] invalid line (redis.redis_test_com.executable /data/redis-server 1475712569) received from client xxx.xxx.xxx.xxx:51010, ignoring
[listener] invalid line (redis.redis_test_com.used_memory_rss_human 7.00M 1475712569) received from client xxx.xxx.xxx.xxx:51010, ignoring
[listener] invalid line (redis.redis_test_com.total_system_memory_human 1.96G 1475712569) received from client xxx.xxx.xxx.xxx:51010, ignoring
[listener] invalid line (redis.redis_test_com.used_memory_lua_human 37.00K 1475712569) received from client xxx.xxx.xxx.xxx:51010, ignoring
[listener] invalid line (redis.redis_test_com.maxmemory_human 0B 1475712569) received from client xxx.xxx.xxx.xxx:51010, ignoring
[listener] invalid line (redis.redis_test_com.maxmemory_policy noeviction 1475712569) received from client xxx.xxx.xxx.xxx:51010, ignoring
[listener] invalid line (redis.redis_test_com.aof_last_write_status ok 1475712569) received from client xxx.xxx.xxx.xxx:51010, ignoring
```

The necessary new keys, if adding them to `SKIP_KEYS_REGEX` is indeed correct, would be

```
executable
used_memory_rss_human
total_system_memory_human
used_memory_lua_human
maxmemory_human
maxmemory_policy
aof_last_write_status
```

**Comment by majormoses** [comment]
@TheKevJames thanks for reporting, could you be willing to have some time to submit a pr for a fix?

**Comment by majormoses** [comment]
I took a look and I feel like this should be passed in as an option so that if this needs to change again as new keys are added in redis users can pass this in without needing maintainer intervention.

**Comment by majormoses** [comment]
@TheKevJames could you please verify that my PR works for you?

**Comment by TheKevJames** [comment]
Hi! I unfortunately no longer have access to the system for which I generated this issue report, however I will take a look at the PR.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-redis/versions/1.2.1
