### ISSUE TITLE
Out-of-date dependency in gemspec causes warnings under sensu 0.29

### ISSUE THREAD

**Issue by flowerysong** [sensu-plugins/sensu-plugins-redis#28]
`/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/redis-3.2.1/lib/redis/client.rb:443: warning: constant ::Fixnum is deprecated`

This should be fixed by https://github.com/redis/redis-rb/commit/9da74357491a77e128474aa929054fa402fc211d, which is included in the redis-rb 3.3.3 release, but sensu-plugins-redis pulls in 3.2.1 specifically.

**Comment by majormoses** [comment]
@flowerysong could you please put together a pr to update the gemspec?

**Comment by flowerysong** [comment]
I started to, but it's a one line change that you should be more than capable of doing on your own and the pull request template is seriously ugly. So, no.

**Comment by majormoses** [comment]
I'm sorry to hear that, when I have some time I will take care of it. If you would like to give feedback feel free to open an issue on: https://github.com/sensu-plugins/sensu-plugins-feature-requests to see if we can make it better.
