### ISSUE TITLE
gem build and release

### ISSUE THREAD

**Issue by sge-babrams** [sensu-plugins/sensu-plugins-redis#7]
It looks like the released gem does not have the the following PR: https://github.com/sensu-plugins/sensu-plugins-redis/pull/6

I verified building the gem locally it works as intended can we get a gem build and publish

**Comment by runningman84** [comment]
I have the same problem, please release an update...

**Comment by mattyjones** [comment]
@runningman84 @sge-babrams built ;)

**Comment by sge-babrams** [comment]
@mattyjones thanks confirmed working
